import React from 'react'
import Head from 'next/head'
import Navbar from './components/New/Navbar';
import Hero from './components/New/Hero';
function Main() {
    return (
        <div>
            <Head>
                <title>SarOakSai</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Hero />
        </div>
    )
}

export default Main