import React from 'react'
import Head from 'next/head'
import Navbar from './components/New/Navbar';
import HeroWithSlider from './components/New/HeroWithSlider';
import Hero from './components/New/Hero';
import SwiperContainer from './components/New/SwiperContainer';

import Genres from './components/New/Genres';
import Trending from './components/New/Trending';
import PopularNow from './components/New/PopularNow';
import Footer from './components/New/Footer';
import ReadNow from './components/New/ReadNow';
function Main() {
    return (
        <div className=' bg-milky'>
            <Head>
                <title>Sar Oak SIne</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <ReadNow />
            <HeroWithSlider />
            <Hero />
            <Genres />
            <Trending />
            <PopularNow />
            <Footer />
        </div>
    )
}

export default Main