import React from 'react'
import Head from 'next/head'
import Navbar from './components/Navbar';
import Bookshowcase from './components/Bookshowcase';
import Slider from './components/Slider';
function Main() {
    return (
        <div>
            <Head>
                <title>SarOakSai</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="mx-5">
                <Slider />
                <Bookshowcase />
            </div>
        </div>
    )
}

export default Main